### ISSUE TITLE
wot

### ISSUE THREAD

**Issue by Matt0704** [SmugBlanco/GenshinMod#3]
I appreciate spreading the word of god, I'm christian myself. But isn't this supposed to be an actual terraria mod?

**Comment by Smug-B** [comment]
This is a terraria mod

I heard other genshin mods have more content though idk

**Comment by Matt0704** [comment]
Well, it is a mod, but no items, or any content at all?

**Comment by Smug-B** [comment]
yeah :p supposed to be a troll mod

**Comment by Matt0704** [comment]
Ohhh I see

**Comment by steviegt6** [comment]
> yeah :p supposed to be a troll mod

Do not refer to any action promoting our Holy Lord as a mere "troll". The spread of God and his word is a serious matter which should not be referred to under such ignorant language. Smug Blanco, my dear friend, I appreciate your kind actions, but you appear to be misguided in this comment.

**Comment by Smug-B** [comment]
> Do not refer to any action promoting our Holy Lord as a mere "troll". The spread of God and his word is a serious matter which should not be referred to under such ignorant language. Smug Blanco, my dear friend, I appreciate your kind actions, but you appear to be misguided in this comment.

May the lord forgive me. Though I have sinned and shall duly be reprimanded in the Kingdom of Satan, I will not pause my devotion to his word in this life nor the next.
